### ISSUE TITLE
Queue is Full Droping

### ISSUE THREAD

**Issue by Bramichou** [dwilches/Ardity#23] opened 2019-05-01 15:18 UTC
Hey There,

First thanks to offer us this amazing lib ! 

I wanted to printLn a number each time in my loop, to get this in the serial monitor but when i send it, it drop a lot of time, and doesnt go to the next line, so i dont know what to do ! Thanks for helping me :) 
<img width="298" alt="Capture d’écran 2019-05-01 à 17 17 42" src="https://user-images.githubusercontent.com/23286738/57024500-0f767a00-6c35-11e9-9a0e-359ff15ccc67.png">

**Comment by dwilches** [comment] 2019-05-01 15:44
Hi Bramichou,
I'm glad you've found Ardity useful.

I don't quite get your question. How are you using Ardity? Is it:
* Your Arduino program prints those numbers, and you want them to appear in Unity's console?
* Or, you're seeing those numbers in Arduino's Serial Monitor (so Ardity is not involved).

And, what do you mean by "it drops lot of times"?

**Comment by Bramichou** [comment] 2019-05-01 16:11
Hello @dwilches Thanks answering me fast :) 

First of all, i will explain you what i want to do : I have a plant connected to my arduino, and i have number which explain the distance between my hand and the plant with a capacitive touch sensor :) 

So i use the Serial controller on Ardity with a Gameobject as Message Listener where i use the event 'OnMessageArrived' to read the messsages. 

So as you saw in the first screen, its what i have on the Arduino's Serials Monitor when i start to listen with unity, and in the Debug Log, i lost a lot of data like this : 

<img width="220" alt="Capture d’écran 2019-05-01 à 18 09 25" src="https://user-images.githubusercontent.com/23286738/57027277-469c5980-6c3c-11e9-813e-b7423851b891.png">

And when i mean "It drops a lot of times", i mean that i lost a lot of time data like have nothing, or have a half of the number ... 

SerialMonitor has 1 as Max Unread Messages, and 1000 as Reconnection delay 


Thank you for your help and to be available to helping me

**Comment by Bramichou** [comment] 2019-05-01 18:57
So did you find why ? @dwilches

**Comment by dwilches** [comment] 2019-05-03 04:14
If I'm understanding correctly, your program generates messages like `521521521`, `521` and even ` ` and all of them are valid (that's what I see in your first image).
And, the problem is when the messages are received in Unity there are some of those that are lost. Is that correct?

The only reason I can think for messages being lost is that there is a disagreement between the baud rates in the Arduino and Unity, can you make sure both are set to 9600?

Also, after each of your Arduino messages, do you have a new-line character?

**Comment by Bramichou** [comment] 2019-05-07 08:20
It's the same baudrate 9600 in Unity and 9600 in Arduiino.

And to answer to your last question, in the Serial Monitor, i got lines with 521521, or only 5, 52 or nothing, so when i want to see what is displayed in the unity logs, i have those lines .. :/

**Comment by tinyboxxx** [comment] 2019-05-07 15:54
I found its relate with framerate, I use [Graphy] to monitor the player's FPS. When I disable Vsync, the frame rate rises from 60 to about 500, and the Queue is Full Dropping problem disappears. 

Although I think the drop old message kinda works anyway.

I think it's a processing problem. I think processing speed should be faster than render speed.

**Comment by dwilches** [comment] 2019-05-07 22:56
Good that you found the issue. You can also try with different standard baud rates, like115200, the higher the number the quicker the data will be transferred.

**Comment by tinyboxxx** [comment] 2019-05-08 03:17
But can we make processing more time per frame? 

For example, if my scene is 60 frame per second, can we receive more than 60 messages per second?

I'm testing with about 105 messages per second (all send from Arduino UNO), when 60 fps, it drops messages, when about 140 fps, it's ok, not dropping.

**Comment by tinyboxxx** [comment] 2019-05-08 03:23
![image](https://user-images.githubusercontent.com/13427224/57346995-53acd180-7183-11e9-8222-2f6d675443da.png)


![image](https://user-images.githubusercontent.com/13427224/57347016-66270b00-7183-11e9-91b8-74df8c487e32.png)

Here is my Serial:
![image](https://user-images.githubusercontent.com/13427224/57347080-a1293e80-7183-11e9-9cca-cc6e8954ca94.png)

![image](https://user-images.githubusercontent.com/13427224/57347101-b1411e00-7183-11e9-80c7-da52e0487a0b.png)

**Comment by Bramichou** [comment] 2019-05-17 10:31
@dwilches i have questions about the build : 

Before to build, to test my app, my workflow was to run my unity game, then i run arduino and open the serial monitor to read data on unity.


But when i build, then i run the app builded for mac, i run after that arduino and opening the serial monitor, but nothing happens ! Do you know why ?

**Comment by dwilches** [comment] 2019-06-08 16:08
Hello,
So you needed to open the serial monitor in the Arduino IDE for data to be seen in Unity?
That shouldn't be necessary, and can even cause issues as there are 2 programs connected by serial to your Arduino. I didn' t even think that was possible.

I don't understand the difference between te 2 scenarios you explain, wasn' t the first one on a Mac too?

Notice the Arduino board is reset and your program restarted when one opens the Serial Monitor, so I wonder if that may be related to the issue you experience.

**Comment by Bramichou** [comment] 2019-06-09 14:19
Okay my bad now it works after building the app but still need to open the serial monitor :D 

How can i say in code, to detect USB port automatically my arduino usb port, to connect directly ? @dwilches

**Comment by dwilches** [comment] 2019-06-09 23:37
I don't know how to detect when a device connects via USB from Unity (or Arduino) but you can try repeatedly sending a command to Unity/Arduino and when it responds successfully then you know the other end of the communication has appeared. I mean, like a ping.

**Closed as completed** 2019-06-09 23:37 UTC
